# Generated by Django 5.2.11 on 2026-02-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='floorplantile',
            new_name='netbox_map__assigne_eb5b30_idx',
            old_name='netbox_map_assigne_idx',
        ),
    ]
