# Generated by Django 5.2.11 on 2026-02-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0004_mapmarker'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mapmarker',
            new_name='netbox_map__assigne_6fd3ec_idx',
            old_name='netbox_map__assigne_mapmarker_idx',
        ),
    ]
