# Generated by Django 5.2.11 on 2026-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0006_mapsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
