# Generated by Django 5.2.11 on 2026-03-09 21:22

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_map', '0015_cablepath_cable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CablePathAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'cable path assignment',
                'verbose_name_plural': 'cable path assignments',
                'ordering': ('cable_path', 'sequence'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cablepathassignment',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.cable'),
        ),
        migrations.AddField(
            model_name='cablepathassignment',
            name='cable_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_assignments', to='netbox_map.cablepath'),
        ),
        migrations.AddField(
            model_name='cablepathassignment',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='cablepath',
            name='cables',
            field=models.ManyToManyField(blank=True, related_name='map_paths', through='netbox_map.CablePathAssignment', to='dcim.cable'),
        ),
        migrations.AlterUniqueTogether(
            name='cablepathassignment',
            unique_together={('cable_path', 'cable')},
        ),
    ]
