# Generated by Django 5.2.11 on 2026-03-10 20:08

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_map', '0016_add_cablepathassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberSplice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('position_a', models.PositiveSmallIntegerField()),
                ('position_b', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'fiber splice',
                'verbose_name_plural': 'fiber splices',
                'ordering': ('device', 'port_a', 'position_a'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='fibersplice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_splices', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='fibersplice',
            name='port_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rearport'),
        ),
        migrations.AddField(
            model_name='fibersplice',
            name='port_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rearport'),
        ),
        migrations.AddField(
            model_name='fibersplice',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='fibersplice',
            unique_together={('device', 'port_a', 'position_a', 'port_b', 'position_b')},
        ),
    ]
