# Generated by Django 5.2.11 on 2026-03-10 20:28

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_map', '0017_add_fibersplice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color.', regex='^#[0-9a-fA-F]{6}$')])),
            ],
            options={
                'verbose_name': 'fiber label',
                'verbose_name_plural': 'fiber labels',
                'ordering': ('rear_port', 'position'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrayLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('tube_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color.', regex='^#[0-9a-fA-F]{6}$')])),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'tray label',
                'verbose_name_plural': 'tray labels',
                'ordering': ('rear_port',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='fiberlabel',
            name='rear_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_labels', to='dcim.rearport'),
        ),
        migrations.AddField(
            model_name='fiberlabel',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='traylabel',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.cable'),
        ),
        migrations.AddField(
            model_name='traylabel',
            name='rear_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tray_label', to='dcim.rearport'),
        ),
        migrations.AddField(
            model_name='traylabel',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddConstraint(
            model_name='fiberlabel',
            constraint=models.UniqueConstraint(fields=('rear_port', 'position'), name='netbox_map_fiberlabel_unique_port_position'),
        ),
    ]
