# Generated by Django 5.2.11 on 2026-03-10 21:29

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_map', '0018_add_traylabel_fiberlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('input_position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('output_position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('split_ratio', models.CharField(blank=True, max_length=10)),
                ('loss_db', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'fiber split',
                'verbose_name_plural': 'fiber splits',
                'ordering': ('device', 'input_port', 'input_position'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='fibersplit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_splits', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='fibersplit',
            name='input_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_inputs', to='dcim.rearport'),
        ),
        migrations.AddField(
            model_name='fibersplit',
            name='output_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_outputs', to='dcim.rearport'),
        ),
        migrations.AddField(
            model_name='fibersplit',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddConstraint(
            model_name='fibersplit',
            constraint=models.UniqueConstraint(fields=('device', 'output_port', 'output_position'), name='netbox_map_fibersplit_unique_output'),
        ),
    ]
