# Generated by Django 5.2.12 on 2026-04-02 17:40

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_map', '0018_application_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_status', models.CharField(default='active', max_length=50)),
                ('default_criticality', models.CharField(default='medium', max_length=50)),
                ('default_environment', models.CharField(default='production', max_length=50)),
                ('default_version', models.CharField(blank=True, max_length=100)),
                ('default_port', models.IntegerField(blank=True, null=True)),
                ('default_protocol', models.CharField(blank=True, max_length=50)),
                ('default_role', models.CharField(default='primary', max_length=50)),
                ('name_format', models.CharField(default='{app}', max_length=200)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='netbox_map.applicationgroup')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'application template',
                'verbose_name_plural': 'application templates',
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
