# Generated by Django 5.2.12 on 2026-04-08 15:33

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0134_owner'),
        ('netbox_map', '0022_applicationdeployment_service'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationdeployment',
            new_name='netbox_map__host_ty_c0097e_idx',
            old_name='netbox_map_appdeploy_host_idx',
        ),
        migrations.RenameIndex(
            model_name='tileportassignment',
            new_name='netbox_map__port_ty_b42bc1_idx',
            old_name='netbox_map_tileportass_port_ty_idx',
        ),
        migrations.AlterField(
            model_name='tileportassignment',
            name='port_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'dcim', 'model__in': ['frontport', 'rearport']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        # Tags (M2M) and custom_field_data changes are metadata-only — no DB schema change needed.
        # Use SeparateDatabaseAndState so Django's migration state stays in sync without
        # attempting impossible ALTER on M2M fields.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='application',
                    name='custom_field_data',
                    field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='tags',
                    field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
                ),
                migrations.AlterField(
                    model_name='applicationdependency',
                    name='custom_field_data',
                    field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                migrations.AlterField(
                    model_name='applicationdependency',
                    name='tags',
                    field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
                ),
                migrations.AlterField(
                    model_name='applicationdeployment',
                    name='custom_field_data',
                    field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                migrations.AlterField(
                    model_name='applicationdeployment',
                    name='tags',
                    field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
                ),
                migrations.AlterField(
                    model_name='applicationgroup',
                    name='custom_field_data',
                    field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                migrations.AlterField(
                    model_name='applicationgroup',
                    name='tags',
                    field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
                ),
                migrations.AlterField(
                    model_name='topologysavedview',
                    name='tags',
                    field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
                ),
            ],
            database_operations=[],
        ),
    ]
