# Generated by Django 5.2.x

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_map', '0023_rename_netbox_map_appdeploy_host_idx_netbox_map__host_ty_c0097e_idx_and_more'),
    ]

    operations = [
        # related_name change on TaggableManager is metadata-only — no DB schema change needed.
        # Use SeparateDatabaseAndState so Django's migration state stays in sync.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='floorplan',
                    name='tags',
                    field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
                ),
            ],
            database_operations=[],
        ),
    ]
