# Generated by Django 6.0.5 on 2026-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0024_floorplan_tags_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='site_map_load_empty',
            field=models.BooleanField(default=False),
        ),
    ]
