# Generated by Django 6.0.5 on 2026-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0025_mapsettings_site_map_load_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='hidden_tile_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
