# Generated by Django 6.0.5 on 2026-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0027_backfill_hidden_tile_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='hidden_tile_types_sitemap',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
