# Generated by Django 6.0.5 on 2026-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0029_backfill_hidden_tile_types_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommarkertype',
            name='icon_foreground',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
