# Generated by Django 6.0.5 on 2026-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0030_custommarkertype_icon_foreground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='floorplan-backgrounds/'),
        ),
    ]
